name: 'Frogo-Loading-Indicator-View'
description: 'Loading for anything your problem to make easier developing android apps'
author: 'Frogobox'
branding:
  icon: archive
  color: green
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
